import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import Toolbar from "@/components/Toolbar";
import { DesktopShortcut } from "@/components/DesktopShortcut";
import FileManager from "@/components/FileManager";
import { useState } from "react";
import PDFViewer from "@/components/PDFViewer";
import SystemContext from "@/contexts/system";
import Education from "@/components/Education";
import About from "@/components/About";
import Experiences from "@/components/Experiences";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [maxZIndex, setMaxZIndex] = useState(10);
  const [fileManagerVisible, setFileManagerVisible] = useState(false);
  const [selectedPDF, setSelectedPDF] = useState("");
  const [educationVisible, setEducationVisible] = useState(false);
  const [aboutVisible, setAboutVisible] = useState(false);
  const [experienceVisible, setExperienceVisible] = useState(false);
  return (
    <SystemContext.Provider value={{
      maxZIndex,
      setMaxZIndex,
      fileManagerVisible,
      setFileManagerVisible,
      selectedPDF,
      setSelectedPDF,
      aboutVisible,
      setAboutVisible,
      educationVisible,
      setEducationVisible,
      experienceVisible,
      setExperienceVisible,
    }}>
      <Head>
        <title>Trieu Vo OS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <FileManager title="File Manager" visible={fileManagerVisible} onClose={() => setFileManagerVisible(false)} />
      <Education title="Education" visible={educationVisible} onClose={() => {
        setEducationVisible(false);
      }} />
      <PDFViewer fileUrl={selectedPDF} title="PDF Viewer" visible={selectedPDF.length > 0} onClose={() => {
        setSelectedPDF("");
      }} />
      <About title="About me" visible={aboutVisible} onClose={() => {
        setAboutVisible(false);
      }} />
      <Experiences title="Experiences" visible={experienceVisible} onClose={() => {
        setExperienceVisible(false);
      }} />
      <Box
        width="100vw"
        height="100vh"
        paddingTop="45px"
        overflow="hidden"
        backgroundImage="url('/wallpaper.jpeg')"
        backgroundSize="cover"
        backgroundPosition="center"
      >
        <DesktopShortcut
          title="File Manager"
          icon="/file-manager.svg"
          onClick={() => setFileManagerVisible(true)}
        />
        <DesktopShortcut title="CV" icon="/file.svg" onClick={() => {
          setSelectedPDF("/cv.pdf");
        }} />
      </Box>
      <Toolbar />
    </SystemContext.Provider>
  );
}
