import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import Toolbar from "@/components/Toolbar";
import { DesktopShortcut } from "@/components/DesktopShortcut";
import FileManager from "@/components/FileManager";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [fileManagerVisible, setFileManagerVisible] = useState(false);
  return (
    <>
      <Head>
        <title>Trieu Vo OS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FileManager visible={fileManagerVisible} />
      <Box
        width="100vw"
        height="100vh"
        overflow="hidden"
        backgroundImage="url('/1dark.jpeg')"
        backgroundSize="cover"
        backgroundPosition="center"
      >
        <DesktopShortcut
          title="File Manager"
          icon="/file-manager.svg"
          onClick={() => setFileManagerVisible(true)}
        />
        <DesktopShortcut title="CV" icon="/file.svg" />
      </Box>
      <Toolbar />
    </>
  );
}
